# run:    conda env create -f environment.yml
# update: conda env update -f environment.yml
name: tlp-metrics
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - seaborn
  - ipykernel
  - pip
  - pip:
    - dvc
    - ddr-p
